---
name: Práctica Aplicación Parcial y Orden Superior
locale: es
type: practice
beta: false
teacher_info: ''
language: haskell
id_format: "%05d"
order:
- 1
- 2
- 3
- 4
- 5
- 118
- 111
- 112
- 119
- 113
- 114
- 115
- 116
private: false
